### PR TITLE
Ultimate Member - Math Captcha in Register form

### PR DESCRIPTION
**Pull request by yuriinalivaiko**
The "Ultimate Member - Math Captcha in Register form" extension is updated to be compatible with the Ultimate Member 2.7.0

### CODE REVIEW

**Comment by champsupertramp** [comment]
Hi @yuriinalivaiko Have you tried the version in the /refactor branch and worked towards it?
https://github.com/ultimatemember/Extended/tree/refactor

The plan is to move all basic extensions and compile as a single plugin with composer, but we will still offer individual extension download in the Release page via Github action.

**Comment by champsupertramp** [comment]
@all-contributors please add @yuriinalivaiko  for maintenance
@all-contributors please add @yuriinalivaiko  for code

**Comment by champsupertramp** [comment]
@all-contributors please add @yuriinalivaiko for maintenance
@all-contributors please add @yuriinalivaiko for code

**Comment by champsupertramp** [comment]
@all-contributors please add @yuriinalivaiko for maintenance
@all-contributors please add @yuriinalivaiko for code

**Comment by champsupertramp** [comment]
Hi @yuriinalivaiko  - I tried adding this to the new extended structure but the library that you require in this pull request is not included. May I know the library you're using so that we can include it in the composer.json?

**Comment by champsupertramp** [comment]
Hi @yuriinalivaiko  - I'm closing this PR due to unresponsiveness. Also found out it has been pushed to this repo. 

https://github.com/umdevelopera/um-math-captcha

Thanks Yurri.

**Comment by yuriinalivaiko** [comment]
Hello @champsupertramp 
I didn't add any new libraries. I used the existing library and just refactored the code a little. I also added language files to make the extension translatable.
Is the "Ultimate Member - Math Captcha in Register form" extension in the Extended package ready to use and translatable? I don't see the POT file for this extension in the package. I'll remove a temporary solution if the current version is completed.
Regards

**Pull request closed without merging**
